/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'scott' at '9/26/16 10:57 AM' with Gradle 3.0
 *
 * @author scott, @date 9/26/16 10:57 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
